### ISSUE TITLE
Switch from PhantomJS to Headless Chrome

### ISSUE THREAD

**Issue by uglow** [odecee/generator-confit#124]
See:
- https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
- https://www.chromestatus.com/feature/5678767817097216

Need to wait for a PhantomJS-like interface to support existing tools (e.g. Karma)

**Comment by Nighthawk14** [comment]
You can use it with existing karma with this configuration:
```js
{
  browsers: ['Chrome_headless'],
  customLaunchers: {
    Chrome_headless: {
      base: 'ChromeCanary',
      flags: ['--headless', '--remote-debugging-port=9222', 'http://0.0.0.0:9876/']
    }
  }
}
```
Do not forget to download Chrome Canary: https://www.google.com.au/chrome/browser/canary.html.

We should switch to the official support once it's merged: 
https://github.com/karma-runner/karma-chrome-launcher/pull/111
