### ISSUE TITLE
How to make Confit more extensible

### ISSUE THREAD

**Issue by uglow** [odecee/generator-confit#25]
In order to make Confit more useful and usable by a wider section of the developer community, it needs to be extensible. See feedback in #24 

I can think of the following ways to to try to make Confit extensible...

### Make it possible for Confit to call other Yeoman generators
This may work by the user installing their own adapter generators and telling the main confit generator (somehow) to use the adapter instead of the default sub-generator.

#### Pros
- Developers can write their own Confit plugins 

#### Cons
- I don't know how to make a Yeoman generator call an external Yeoman generator, and ensure that the external generator has access to the internal configuration files. Perhaps this could only be done by creating sub-generators?

### Add support in `confit.json` for extension points, to run external-to-Confit Node commands

In this approach, the **generated config** is extensible, rather than the generator itself. This could look like this:

```console
// confit.json
{
  "release": {
    "someProperty": "..."
    // Developer can customise this next line directly
    "tasks": ["runAllTests", "generateDocs", "myCustomScript --val=true", "commit", "publish"]
  }
```

Alternatively, since Confit uses NPM for task configuration, it might be possible to allow developers to edit the `package.json` scripts and when `yo confit` rebuilds the tools, to not change user-edited scripts?

```console
// package.json
{
  "scripts": {
    // "myCustomScript" is (somehow) not overwritten when Conift is re-run
    "dev": "npm-run-all clean:dev verify myCustomScript --parallel verify:watch build:dev serve:dev"
  }
```

### Pros
- This is more in-line with the Confit vision, whereby standard processes are supported, but developers can extend the config without fear that it will be over-written

### Cons
- ???

Thoughts? @mboudreau, @timweightman @kerenBurshtein @mikrich

**Comment by kerenBurshtein** [comment]
Which one would make the product more complex to use?

**Comment by mboudreau** [comment]
@kerenBurshtein I don't think it would make things more complex since the user could still simply answer questions and get a build to start with.  This is more of how can we make confit do things that it doesn't know about for a specific use case.

@uglow I say for now, only making the config extensible is more than enough.  We can look into sub generators in the future, but for now, I just want to be able to specify a few things after the original setup.

As for how it works, using npm is a way of doing it, another would be to have a way to abstract the confit tasks based on the build system chosen by the user.  Could be a simple as having a file with a particular task name which is standard for all confit based configs.

**Comment by uglow** [comment]
@mboudreau @kerenBurshtein considering your feedback and requirements in #24, I think the best option for now would be this one:

```console
// confit.json
{
  "release": {
    "someProperty": "..."
    // Developer can customise this next line directly
    "tasks": ["runAllTests", "generateDocs", "myCustomScript --val=true", "commit", "publish"]
  }
```

**Strategy**
- The first time Confit is run, it populates the `tasks` property.
- Subsequent runs:
  - If Confit should never overwrite this property, how will future enhancements to Confit that add features like `generateDocs` be added to the `tasks`?
  - If Confit *can* overwrite this property, how can it do it safely? For text files, we can insert "Confit generated" blocks which Confit can safely overwrite without changing the rest of the file. We need a similar mechanism here.
  - We could simplify the problem by keeping the Confit tasks together as a unit, so you could only add tasks before-or-after the Confit tasks.: 
```
"tasks: ["myPreTaskScript --val=true", "confitReleaseTasks", "myPostTaskScript"]
```
or
```
"preTasks": ["myPreTaskScript --val=true"]
"postTasks": ["myPostTaskScript"]`
```
I think this last approach is the most sustainable. What do you think?

**Comment by mboudreau** [comment]
I don't think this will work since I still can't 'inject' my own tasks between the confit ones.

Instead, how about you put all tasks under the same task array, but prefix all confit tasks with "confit:...", this way confit specific tasks are very apparent.

**Comment by uglow** [comment]
Labelling tasks with `confit:...` will identify which tasks are "owned" by Confit, but will not allow non-destructive upgrading of tasks. For example:

confit.json before upgrade, modified by user:
```
"tasks": ["confit:build", "myPreTaskScript --val=true", "confit:release", "myPostTaskScript"]
```

confit.json upgrade, modified by Confit generator:
```
"tasks": ["confit:build", "confit:generateDocs", "confit:release"]
```

If the burden of changing this back to `confit:build, preTask, confit:generateDocs, confit:release, postTask` rests with the **developer**, then I think that's workable. If it rests with Confit, it is *not* workable because Confit cannot know how to re-place the user-defined tasks amongst it's own tasks.

**Comment by mboudreau** [comment]
The problem I have with that is that my specific tasks needs to be injected between confit tasks.

Maybe we should just use the NPM standard for tasks, where we can append 'pre' or 'post' to any task to run then in order.  For example:

```
{
    // Confit specific tasks here which should depict the entire workflow, this shouldn't change and will be overwritted in an upgrade
    confitTasks: [ 'build', 'generateDocs', 'release' ],
    
    // If the user wants to inject custom tasks, they can do so by specifying the confit task and prefixing either 'pre' or 'post' to the specific tasks.
    prebuild: 'grunt lint',
    postrelease: 'aws s3 upload dist.zip'
}
```

If we wanted to be really clever, we could have a way for custom tasks to run an array of other tasks so it's easier to split it up and then pick and choose.  By using this moving forward, we should be able to fix any upgrading issues as long as we don't remove tasks, but we can still have an upgrade plan for that.

**Comment by uglow** [comment]
@mboudreau - agree that using the existing NPM mechanism for changing tasks would be best for now.

If no objections, I will close this issue in 3 days.

**Comment by mboudreau** [comment]
Sounds good to me :)
