### ISSUE TITLE
Enable browser synchronisation in protractor for angular app 

### ISSUE THREAD

**Issue by Nighthawk14** [odecee/generator-confit#61]
When creating an angular app with confit the protractor configuration is set up like that:

```js
onPrepare: function() {
    // Turn off the angular-sync part-of-Protractor, as we are using Protractor in a generic way
    browser.ignoreSynchronization = true;

    return browser.getProcessedConfig().then(function(config) {
      // Attach the reporters
      config.reportWriters.forEach(function(fn) {
        fn();
      });
    });
  },
```

Protractor should probably not ignoreSynchronization by default for an angular app.

**Comment by uglow** [comment]
This configuration is currently used for both Angular & non-Angular browser projects. The solution will be to wrap this line in an EJS template that conditionally renders the line if the framework is 'Angular 1.x'
