### ISSUE TITLE
Update to use codecept.io

### ISSUE THREAD

**Issue by Nighthawk14** [odecee/generator-confit#62]
Protractor 4.0.0 has been released and contains some good features. As well it now has typings for typescript. 👍

**Comment by uglow** [comment]
Maybe this issue could be changed to use codecept.io once it is stable. Thoughts?

**Comment by Nighthawk14** [comment]
Definitely 👍. I'm waiting for the PR to be merged https://github.com/Codeception/CodeceptJS/pull/167

**Comment by Nighthawk14** [comment]
Some feedback on this, I would still suggest to upgrade protractor to 4.0.10 now, codecept is an interesting tool but we found some annoying things after using it here :), it's mostly bugs but that means it's not quite ready yet.

**Comment by uglow** [comment]
Thanks @Nighthawk14 . Can you elaborate on the bugs you found, please?
