### ISSUE TITLE
Upgrade to webpack 2

### ISSUE THREAD

**Issue by Nighthawk14** [odecee/generator-confit#86]
Very soon the new major version of webpack will be release with some cool features.
You can find new documentation here https://webpack.js.org/. I think they are still waiting on enhancements on this documentation before releasing.
The config needs just some small changes to be compatible, then we can work out on implementing new features.
Webpack 2 is supporting ES2015 modules, that means we don't need babel to compile them and we will have a gain in file size and performances. :)

**Comment by uglow** [comment]
We still may need for the rest of the ES2015+ features that are not supported in the targeted browsers.

**Comment by Nighthawk14** [comment]
@uglow Yes sorry I should have explained more, we should not remove babel completely but just tell him not to transpile modules: 
```json
"presets": [
  ["es2015", { "modules": false }]
]
```
